### ISSUE TITLE
勤怠表出力時のxlsxファイル作成関数

### ISSUE THREAD

**Issue by minari515** [FUJI-CORPORATION-GROUP/Attendance_format#12]
GASの関数でつくりたい

なんならボタン押したら合計から個々のシート作成→名前を任意のにしてダウンロードまで行けたらかなり楽

**Comment by tagahei** [comment]
- シートごとExcelにしてダウンロード
- 別スプシ作成してダウンロード

**Comment by tagahei** [comment]
候補
- GoogleDriveにスプシを吐き出す
  - ダウンロードが必要だが，Webで保存できるのはいいよね
- ローカルにExcelをダウンロード
  - なんか，いろいろ調べた感じ難しそう

**Comment by tagahei** [comment]
- [【GAS】CSVファイルをローカル(パソコン)に出力する方法(Gスプレッドシート)](https://technical.verybestcbp.com/downloadcsv/)

スプシ-> Excel
- [【Google Apps Script（GAS）】スプレッドシート（大量）を一括でExcelに変換する方法【業務効率化】](https://note.com/taraco123/n/nd704da152f69)
  - シートごとじゃない
- [【GAS】スプレッドシート⇒エクセル変換時短術](https://www.one-walker.net/gas-excel-henkan/)
  - シートごとだけどinsertが動かない

**Comment by tagahei** [comment]
別スプシにシート指定して生成はできた

**Comment by tagahei** [comment]
ローカルにダウンロードしたい


- [GASで特定のシートのデータをCSVでローカルにダウンロードする方法（Part3）](https://eguweb.jp/gas/66500/)
